
- hosts: local
  sudo: True
  vars:
    home: "/home/{{ansible_env['SUDO_USER']}}"
    server_dir: "{{home}}/wikipedia-android-app-server"
    wikimedia_repo: "https://github.com/wikimedia"

  tasks:
  - name: Update Apt cache
    apt: update_cache=yes

  - name: Install CURL
    apt: pkg=curl state=installed

  - name: Install Apt HTTPS support
    apt: pkg=apt-transport-https state=installed

  - name: Check for nodesource Apt sources
    stat: path=/etc/apt/sources.list.d/nodesource.list
    register: nodesourcelist

  - name: Add Nodesource Apt Sources List Deb
    shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    register: nodesourceadded
    when: nodesourcelist.stat.exists == False

  - name: Install NodeJS
    apt: pkg=nodejs state=latest
    when: nodesourcelist.stat.exists or nodesourceadded|success

  - name: Install build-essential
    apt: pkg=build-essential state=installed

  - name: Install forever
    npm: name=forever global=yes

  - name: Checkout RESTBASE git repo
    git: repo={{wikimedia_repo}}/restbase.git
         dest={{server_dir}}/restbase
         version=66b6440127e626e54c95b7cf3a40f0d0ccf151da

  - name: Checkout parsoid git repo
    git: repo={{wikimedia_repo}}/parsoid.git
         dest={{server_dir}}/parsoid
         version=36075c7fc242ad2fd7bba05661606722ebda49aa

  - name: Checkout mobileapps git repo
    git: repo={{wikimedia_repo}}/mediawiki-services-mobileapps.git
         dest={{server_dir}}/mobileapps
         version=09543312d52941dbc7a4523bc9107d02b826acc8

  - name: Install RESTBASE npm deps
    npm: path={{server_dir}}/restbase

  - name: Install parsoid npm deps
    npm: path={{server_dir}}/parsoid

  - name: Install mobileapps npm deps
    npm: path={{server_dir}}/mobileapps
