services:
  - name: restbase
    module: hyperswitch
    conf:
      port: {{restbase_port}}
      salt: secret
      default_page_size: 125
      user_agent: RESTBase
      spec:
        x-sub-request-filters:
          - type: default
            name: http
            options:
            allow:
              - pattern: {{api_url}}
                forward_headers: true
              - pattern: http://localhost:{{parsoid_port}}
                forward_headers: true
              - pattern: /^https?:\/\//
        paths:
          /{domain:localhost}:
            x-modules:
              - path: project.yaml
                options:
                  action:
                    apiUriTemplate: {{api_url}}
                  parsoid:
                    host: http://localhost:{{parsoid_port}}
                  mobileapps:
                    host: http://localhost:{{mobileapps_port}}
                  table:
                    backend: sqlite
                    dbname: db.sqlite3
                    pool_idle_timeout: 20000
                    retry_delay: 250
                    retry_limit: 10
                    show_sql: false

info:
  name: restbase

logging:
  name: restbase
  level: info
